### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by mkiii** [jwyllie83/tcpping#4]
Can I compile one version for openwrt_x86_64 ?
And what is the git source of tcpping ?
Thank you for reply.

**Comment by jwyllie83** [comment]
Hey mkiii, yes, you should be able to.  The makefile should work as-is on your openwrt machine.  I don't have one myself so I've never tried it, but I have taken patches from people who claim to have it working.  To do so, you'll need to have a full compilation environment for your openwrt machine, or cross-compile it from your local environment.  The following guide looks better than anything I can type out:

https://wiki.openwrt.org/doc/devel/packages

The source is available here on Github; this is the canonical location of the code.  You can check it out using any standard method.

**Comment by mkiii** [comment]
Thank you very much.

**Comment by jwyllie83** [comment]
You're welcome.  Good luck!
